config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # 学习中心
  # namespace :dashboard do
  #   # get :get_dashboard
  #   resources :courses
  # end

  resources :dashboard, only: [:index]

  #文章
  resources :posts, only: [:show]
  resources :posts do
    member do
      post :add_to_favorite
      post :quit_favorite
    end
  end

  # meetup
  resources :meetup_groups

  # 编程比赛
  resources :competitions

  # 直播室
  namespace :live do
    get :get_live
  end

  # 帮助文档
  namespace :docs do
    get :get_docs
  end

  # 交流论坛
  namespace :forum do
    get :get_forum
  end


  # 某个课程
  resources :courses do
    get 'syllabus', to: 'courses#get_syllabus'

    namespace :assignments do
      get :get_assignments
    end
    namespace :faqs do
      get :get_faqs
    end
    namespace :activities do
      get :get_activities
    end
    namespace :leaderboard do
      get :get_leaderboard
    end
  end

  # 节主体内容
  # resources :posts

  # 作业
  resources :tasks, only: [:show]
  resources :tasks do
    # 答案
    resources :other_answers
  end


  namespace :admin do
    root to: "dashboard#index"
    get 'dashboard', to: 'dashboard#index'
    get 'tools', to: 'tools#index'

    resources :courses do
      member do
        post :lock
        post :unlock
      end

      resources :chapters
    end

    # 节 crud
    resources :chapters do
      resources :sections
    end

    # 作业 rd
    resources :assignments, only: [:index, :show, :destroy]
    # 作业 cu
    resources :sections do
      resources :assignments
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @assignment = Assignment.find(params[:id])
    @chapter = @assignment.section.chapter
    @course = @chapter.course
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/show.html.erb
<%= title "作业 - " %>
<%= render :partial => "courses/course_item" %>
<div class="content-wrap">
  <div class="container">
    <div class="course-block">
      <div class="task-show-title clearfix">
        <h3 class="pull-left">
          <%= @assignment.assignment_name %>
        </h3>
        <div class="pull-right">
          已有 418 个第二期同学提交了这个作业
          <a class="opt-btn" href="/tasks/273/other_answers?order=recent"><i class=""></i><span> 看看同学</span></a>

        </div>
      </div>
      <br>
      <div class="post-link">
        <span>所属教材：</span><br>
        <%= link_to(@chapter.chapter_name, post_path(@assignment.section)) %>
      </div>

      <div class="content-font">
        <div>
          <span>作业内容：</span>
        </div>
        <p><%= @assignment.description%></p>
      </div>

    </div>
  </div>
</div>