config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # 学习中心
  # namespace :dashboard do
  #   # get :get_dashboard
  #   resources :courses
  # end

  resources :dashboard, only: [:index]

  #文章
  resources :posts, only: [:show]
  resources :posts do
    member do
      post :add_to_favorite
      post :quit_favorite
    end
  end

  # meetup
  resources :meetup_groups

  # 编程比赛
  resources :competitions

  # 直播室
  namespace :live do
    get :get_live
  end

  # 帮助文档
  namespace :docs do
    get :get_docs
  end

  # 交流论坛
  namespace :forum do
    get :get_forum
  end


  # 某个课程
  resources :courses do
    get 'syllabus', to: 'courses#get_syllabus'

    namespace :assignments do
      get :get_assignments
    end
    namespace :faqs do
      get :get_faqs
    end
    namespace :activities do
      get :get_activities
    end
    namespace :leaderboard do
      get :get_leaderboard
    end
  end

  # 节主体内容
  # resources :posts

  # 作业
  resources :tasks, only: [:show]
  resources :tasks do
    # 答案
    resources :other_answers
  end


  namespace :admin do
    root to: "dashboard#index"
    get 'dashboard', to: 'dashboard#index'
    get 'tools', to: 'tools#index'

    resources :courses do
      member do
        post :lock
        post :unlock
      end

      resources :chapters
    end

    # 节 crud
    resources :chapters do
      resources :sections
    end

    # 作业 rd
    resources :assignments, only: [:index, :show, :destroy]
    # 作业 cu
    resources :sections do
      resources :assignments
    end
  end

end

app/models/section.rb
# == Schema Information
#
# Table name: sections
#
#  id             :integer          not null, primary key
#  section_name   :string
#  is_exist_video :boolean
#  chapter_id     :integer
#  content        :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Section < ApplicationRecord
  belongs_to :chapter
  # belongs_to :user
  has_many :section_relationships

  #has_learned or has_collected TODO
  has_many :members, through: :section_relationships, source: :user

  has_many :assignments

  has_many :favorites
  has_many :users, through: :favorites, source: :user

  # 本节作业数
  def assignments_count
    self.assignments.length
  end

end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  layout "admin"

  def index
    @chapter = Chapter.find(params[:chapter_id])
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    
    redirect_to :back
  end

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.new
  end

  def create
    # 关联到章
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.new(section_params)
    @section.chapter = @chapter

    if @section.save
      # 创建章节后返回课程章节目录
      redirect_to admin_course_path(@chapter.course)
      flash[:notice] = "创建成功！"
    else
      render :new
      flash[:warning] = "创建失败！#{ @section.errors.full_messages }"
    end
  end

  def edit
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to admin_course_path(@chapter.course)
    else
      render :edit
    end
  end

  private
  def section_params
    params.require(:section).permit(:section_name, :is_exist_video, :content)
  end
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
  def markdown(text)
		renderer_options = {
			hard_wrap: true,
			filter_html: true
		}

		markdown_options = {
			autolink: true,
			no_intra_emphasis: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}

		renderer = HTMLwithRouge.new(renderer_options)
		Redcarpet::Markdown.new(renderer, markdown_options).render(text).html_safe
	end

	class HTMLwithRouge < Redcarpet::Render::HTML

		INDENT = " " * 2

		def block_code(code, metadata)
			language, filename = metadata.split(":") if metadata

			lexer = find_lexer_with(language)

			formatter = Rouge::Formatters::HTML.new
			formatter2 = Rouge::Formatters::HTMLTable.new(formatter, opts={})

			rows = []
			rows << %(<div class="code-block">)
			if filename
				rows << %(#{INDENT}<div class="code-header">)
				rows << %(#{INDENT * 2}<span>#{filename}</span>)
				rows << %(#{INDENT}</div>)
			else
				rows << %(#{INDENT}<div class="code-header">)
				rows << %(#{INDENT * 2}<span>&nbsp</span>)
				rows << %(#{INDENT}</div>)
			end
			rows << %(#{INDENT}<div class="code-body">)
			rows << %(#{INDENT * 2}#{formatter2.format(lexer.lex(code))})
			rows << %(#{INDENT}</div>)
			rows << %(</div>)
			rows.join("\n")
		end

		def find_lexer_with(language)
			downcase_language = language.try(:downcase)
			case downcase_language
			when "rb", "ruby"
				lexer = DiffRuby
			when "html"
				lexer = DiffHTML
			when "erb"
				lexer = DiffErb
			when "js", "javascript"
				lexer = DiffJS
			else
				lexer = Rouge::Lexer.find(downcase_language) || lexer = Rouge::Lexers::PlainText
			end
		end
	end

	class DiffRuby < Rouge::Lexers::Ruby
		prepend :root do
			rule(/^\+.*$\n?/, Generic::Inserted)
			rule(/^-+.*$\n?/, Generic::Deleted)
		end
	end

	class DiffHTML < Rouge::Lexers::HTML
		prepend :root do
			rule(/^\+.*$\n?/, Generic::Inserted)
			rule(/^-+.*$\n?/, Generic::Deleted)
		end
	end

	class DiffErb < Rouge::Lexers::ERB
		prepend :root do
			rule(/^\+.*$\n?/, Generic::Inserted)
			rule(/^-+.*$\n?/, Generic::Deleted)
		end
	end

	class DiffJS < Rouge::Lexers::Javascript
		prepend :root do
			rule(/^\+.*$\n?/, Generic::Inserted)
			rule(/^-+.*$\n?/, Generic::Deleted)
		end
	end

	class DiffCoffee < Rouge::Lexers::Coffeescript
		prepend :root do
			rule(/^\+.*$\n?/, Generic::Inserted)
			rule(/^-+.*$\n?/, Generic::Deleted)
		end
	end
end

app/views/admin/sections/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
     编辑小节
    <small>所属章节：<%= @section.chapter.chapter_name %></small>
  </h1>

  <!-- 面包屑 -->
  <ol class="breadcrumb">
    <li><%= link_to("首页", admin_dashboard_path) %></li>
    <li><%= link_to("课程目录", admin_course_path(@chapter.course)) %></li>
    <li class="active">小节编辑</li>
  </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">小节</h3>

        </div>
        <div class="box-body">
          <%= simple_form_for [:admin, @chapter, @section] do |f| %>

              <%= f.input :section_name, label: "小节名称" %>
              <%= f.input :is_exist_video, label: "是否有视频"%>
              <%= f.input :content, label: "本节内容"%>

            <%= f.submit "提交", data: { disable_with: "提交中..." }, class: "btn btn-primary" %>

          <% end %>
        </div>

      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
</section>


 <div id="gotop">
   <i class="fa fa-arrow-up" aria-hidden="true"></i>
 </div>

app/views/admin/sections/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
     新增小节
    <small>所属章节：<%= @chapter.chapter_name %></small>
  </h1>

  <!-- 面包屑 -->
  <ol class="breadcrumb">
    <li><%= link_to("首页", admin_dashboard_path) %></li>
    <li><%= link_to("课程目录", admin_course_path(@chapter.course)) %></li>
    <li class="active">新增小节</li>
  </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">小节</h3>

        </div>
        <div class="box-body">
          <%= simple_form_for [:admin, @chapter, @section] do |f| %>

              <%= f.input :section_name, label: "小节名称" %>
              <%= f.input :is_exist_video, label: "是否有视频"%>
              <%= f.input :content, label: "本节内容"%>

            <%= f.submit "提交", data: { disable_with: "提交中..." }, class: "btn btn-primary" %>

          <% end %>
        </div>

      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
</section>


 <div id="gotop">
   <i class="fa fa-arrow-up" aria-hidden="true"></i>
 </div>

app/views/admin/sections/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= @section.section_name %>
    <small>所属章节：<%= @section.chapter.chapter_name %></small>
  </h1>

  <!-- 面包屑 -->
  <ol class="breadcrumb">
    <li><%= link_to("首页", admin_dashboard_path) %></li>
    <li><%= link_to("课程目录", admin_course_path(@section.chapter.course)) %></li>
    <li class="active">小节详情</li>
  </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">小节详情</h3>
          <!-- tools box -->
          <div class="pull-right box-tools">
            <%= link_to(edit_admin_chapter_section_path(@section.chapter, @section), :class => "btn btn-xs btn-default") do%>
              <span class="fa fa-edit" title ="编辑小节">节</span>
            <% end %>
            <%= link_to(new_admin_section_assignment_path(@section), :class => "btn btn-xs btn-default") do%>
              <span class="fa fa-plus" title ="新增作业">作</span>
            <% end %>
          </div>
          <!-- /. tools -->
        </div>
        <div class="box-body">
          <div class="markdown">
            <% if @section.content %>
              <%= markdown(@section.content) %>
            <% else %>
              暂无内容
            <% end %>

           </div>

           <div class="assignment-area">
             <h3>本节作业(<%= @section.assignments_count %>)</h3>
             <ul class="list-group">
               <% @section.assignments.each_with_index do |assignment, i| %>
                 <li class="list-group-item">
                   <div class="pull-right">
                     <%= link_to(edit_admin_section_assignment_path(@section, assignment), :class => "btn btn-xs btn-default") do%>
                       <span class="fa fa-edit" title ="编辑作业"></span>
                     <% end %>
                   </div>

                   <%= i+1 %>.
                   <!-- <%= link_to(assignment.assignment_name, admin_section_assignment_path(@section, assignment)) %> -->
                   <b><%= assignment.assignment_name %></b>
                   <% if assignment.assignment_name %>
                     <%= markdown(assignment.description) %>
                   <% else %>
                     暂无内容
                   <% end %>
                 </li>
               <% end %>
             </ul>
           </div>
        </div>

      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
</section>


 <div id="gotop">
   <i class="fa fa-arrow-up" aria-hidden="true"></i>
 </div>