config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # 学习中心
  # namespace :dashboard do
  #   # get :get_dashboard
  #   resources :courses
  # end

  resources :dashboard, only: [:index]

  #文章
  resources :posts, only: [:show]
  resources :posts do
    member do
      post :add_to_favorite
      post :quit_favorite
    end
  end

  # meetup
  resources :meetup_groups

  # 编程比赛
  resources :competitions

  # 直播室
  namespace :live do
    get :get_live
  end

  # 帮助文档
  namespace :docs do
    get :get_docs
  end

  # 交流论坛
  namespace :forum do
    get :get_forum
  end


  # 某个课程
  resources :courses do
    get 'syllabus', to: 'courses#get_syllabus'

    namespace :assignments do
      get :get_assignments
    end
    namespace :faqs do
      get :get_faqs
    end
    namespace :activities do
      get :get_activities
    end
    namespace :leaderboard do
      get :get_leaderboard
    end
  end

  # 节主体内容
  # resources :posts

  # 作业
  resources :tasks, only: [:show]
  resources :tasks do
    # 答案
    resources :other_answers
  end


  namespace :admin do
    root to: "dashboard#index"
    get 'dashboard', to: 'dashboard#index'
    get 'tools', to: 'tools#index'

    resources :courses do
      member do
        post :lock
        post :unlock
      end

      resources :chapters
    end

    # 节 crud
    resources :chapters do
      resources :sections
    end

    # 作业 rd
    resources :assignments, only: [:index, :show, :destroy]
    # 作业 cu
    resources :sections do
      resources :assignments
    end
  end

end

app/views/common/_admin_footer.html.erb
<!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Version 1.0.0
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">我的公司</a>.</strong> All rights reserved.
  </footer>

app/views/common/_admin_navbar.html.erb
<header class="main-header">

    <!-- Logo -->
    <a href="/admin" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>D</b>Y</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>豆优</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="javascript:void(0)" onclick="toggleSidebar()" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- User Account Menu -->
          <% if !current_user %>
              <li><%= link_to("注册", new_user_registration_path) %> </li>
              <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
            <% else %>
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <!-- <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->
              <!-- <%= image_tag "/vendor/assets/adminlte/dist/img/user2-160x160.jpg", class: "user-image", alt: "User Image" %> -->
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs"><%= current_user.email %></span>
            </a>
            <ul class="dropdown-menu">
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <%= link_to("客户端", root_path, class: "btn btn-default btn-flat") %>
                </div>
                <div class="pull-right">
                  <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out btn btn-default btn-flat'), destroy_user_session_path, method: :delete) %>
                </div>
              </li>
            </ul>
          </li>
          <% end %>
          <!-- Control Sidebar Toggle Button -->
          <!-- <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li> -->
        </ul>
      </div>
    </nav>
  </header>

app/views/common/_admin_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">学习中心</li>
      <!-- Optionally, you can add icons to the links -->
      <li class="<%= is_sidebar_active(["dashboard", "courses", "chapters", "sections"]) %>"><a href="<%= admin_dashboard_path %>"><i class="fa fa-th"></i> <span>课程管理</span></a></li>
      <li class="<%= is_sidebar_active(["assignments"]) %>"><a href="<%= admin_assignments_path %>"><i class="fa fa-edit"></i> <span>作业管理</span></a></li>
      <li class="<%= is_sidebar_active(["tools"]) %>"><a href="<%= admin_tools_path %>"><i class="fa fa-internet-explorer"></i> <span>网站分析工具</span></a></li>

      <!-- <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="#">Link in level 2</a></li>
          <li><a href="#">Link in level 2</a></li>
        </ul>
      </li> -->
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<!-- footer -->
<div id="footer" class="footer">
	<div class="contact">
		<a href="#" class="weixin">
      <%= image_tag("index/weixin_icon.png") %>
    </a>
		<a href="#">
      <%= image_tag("index/weibo_icon.png") %>
    </a>
	</div>
	<ul class="des_block">
		<li class="line"><a href="#">企业合作</a></li>
		<li class="line"><a href="#">人才招聘</a></li>
		<li class="line"><a href="#">关于我们</a></li>
		<li><a href="#">联系我们</a></li>
	</ul>
	<p class="copyright">Copyright©️2013-2017 上道教育  All Right </p>
</div>
<!-- footer end-->

app/views/common/_navbar.html.erb
<nav class="layout-header">
	<div class="container_wrap">
		<h1 class="logo left">
			<!-- <%= image_tag("index/logo.png", :width => "100") %> -->
			<a class="navbar-brand" href="/">
				<i class="fa fa-diamond" aria-hidden="true"> 上道教育</i>
			</a>
		</h1>
		<ul class="wrap_left left">
			<li><a href="/dashboard?category=basic">学习中心</a></li>
			<!-- <li><a href="#">个人中心</a></li> -->
		</ul>
		<div class="wrap_right right">
			<!-- <div class="search left">
				<input type="text" name="search">
				<span class="search_icon"></span>
			</div> -->
			<ul class="left">
        <% if !current_user %>
  				<li class="left login_btn"><%= link_to("登录", new_user_session_path) %></li>
  				<li class="left signup_btn"><%= link_to("注册", new_user_registration_path) %></li>
        <% else %>
          <li class="dropdown" style="margin-top:6px;">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi!, <%= current_user.email %>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <% if current_user.admin? %>
                <li> <%= link_to("管理后台", admin_dashboard_path) %> </li>
								<li class="divider"></li>
                <% end %>
                <li> <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% end %>
			</ul>
		</div>
	</div>
</nav>