config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # 学习中心
  # namespace :dashboard do
  #   # get :get_dashboard
  #   resources :courses
  # end

  resources :dashboard, only: [:index]

  #文章
  resources :posts, only: [:show]
  resources :posts do
    member do
      post :add_to_favorite
      post :quit_favorite
    end
  end

  # meetup
  resources :meetup_groups

  # 编程比赛
  resources :competitions

  # 直播室
  namespace :live do
    get :get_live
  end

  # 帮助文档
  namespace :docs do
    get :get_docs
  end

  # 交流论坛
  namespace :forum do
    get :get_forum
  end


  # 某个课程
  resources :courses do
    get 'syllabus', to: 'courses#get_syllabus'

    namespace :assignments do
      get :get_assignments
    end
    namespace :faqs do
      get :get_faqs
    end
    namespace :activities do
      get :get_activities
    end
    namespace :leaderboard do
      get :get_leaderboard
    end
  end

  # 节主体内容
  # resources :posts

  # 作业
  resources :tasks, only: [:show]
  resources :tasks do
    # 答案
    resources :other_answers
  end


  namespace :admin do
    root to: "dashboard#index"
    get 'dashboard', to: 'dashboard#index'
    get 'tools', to: 'tools#index'

    resources :courses do
      member do
        post :lock
        post :unlock
      end

      resources :chapters
    end

    # 节 crud
    resources :chapters do
      resources :sections
    end

    # 作业 rd
    resources :assignments, only: [:index, :show, :destroy]
    # 作业 cu
    resources :sections do
      resources :assignments
    end
  end

end

app/models/chapter.rb
# == Schema Information
#
# Table name: chapters
#
#  id            :integer          not null, primary key
#  chapter_name  :string
#  learning_time :integer
#  course_id     :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Chapter < ApplicationRecord
  belongs_to :course
  has_many :sections
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  layout "admin"

  def index
    @course = Course.find(params[:course_id])
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    redirect_to :back
  end

  def new
    @course = Course.find(params[:course_id])
    @chapter = Chapter.new
  end

  def create
    # 关联到课程
    @course = Course.find(params[:course_id])
    @chapter = Chapter.new(chapter_params)
    @chapter.course = @course

    if @chapter.save
      # redirect_to admin_course_chapters_path
      # 创建章节后返回课程章节目录
      redirect_to admin_course_path(@course)
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:course_id])
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])

    if @chapter.update(chapter_params)
      redirect_to admin_course_path(@chapter.course)
    else
      render :edit
    end
  end

  private
  def chapter_params
    params.require(:chapter).permit(:chapter_name, :learning_time)
  end
end

app/helpers/admin/chapters_helper.rb
module Admin::ChaptersHelper
end

app/views/admin/chapters/_form.html.erb
<%= simple_form_for [:admin, @course, @chapter] do |f| %>

    <%= f.input :chapter_name, label: "章节名称" %>
    <%= f.input :learning_time, label: "预计学习时间" %>
  <%= f.submit "提交", data: { disable_with: "提交中..." }, class: "btn btn-primary" %>

<% end %>

app/views/admin/chapters/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    编辑章节
    <small></small>
  </h1>

  <ol class="breadcrumb">
    <li><a href="/admin"><i class="fa fa-dashboard"></i> 首页</a></li>
    <li><%= link_to("课程目录", admin_course_path(@chapter.course)) %></li>
    <li class="active">编辑章节</li>
  </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-body">
          <div class="form-wrap">
            <%= render "form" %>
          </div>
        </div>

      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
</section>

app/views/admin/chapters/index.html.erb
<div class="content">
  <div class="row">
    <div class="span12">
      <div class="group toolbar-normal clearfix">
        <%= link_to(" 新增章节", new_admin_course_chapter_path, :class => "btn btn-primary fa fa-plus pull-right" ) %>
      </div>
      <div class="course-list">
        <table class="table table-bordered table-hover">
          <thead >
              <tr class="active">
                  <td>章节名</td>
                  <td>管理</td>
              </tr>
          </thead>
          <tbody>
            <% @chapters.each do |chapter| %>
            <tr>
              <td><%= link_to(chapter.chapter_name, admin_course_chapter_path(@course, chapter)) %></td>

              <td>
                <%= link_to(edit_admin_course_chapter_path(@course, chapter), :class => "btn btn-xs btn-default") do%>
                  <span class="fa fa-edit" title ="编辑"></span>
                <% end %>

                <%= link_to(admin_course_chapter_path(@course, chapter), :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure?" }) do%>
                  <span class="fa fa-remove" title="删除"></span>
                <% end %>
            </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/chapters/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    新增章节
    <small></small>
  </h1>

  <ol class="breadcrumb">
    <li><a href="/admin"><i class="fa fa-dashboard"></i> 首页</a></li>
    <li><%= link_to("课程目录", admin_course_path(@course)) %></li>
    <li class="active">新增章节</li>
  </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-body">
          <div class="form-wrap">
            <%= render "form" %>
          </div>
        </div>

      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
</section>

app/views/admin/chapters/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    章节详情
  </h1>

  <ol class="breadcrumb">
    <li><%= link_to("首页", admin_dashboard_path) %></li>
    <li><%= link_to("课程目录", admin_course_path(@chapter.course)) %></li>
    <li class="active">章节详情</li>
  </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title"><%= @chapter.chapter_name %></h3>
        </div>
        <div class="box-body">
          <ul class="list-group">
            <% @chapter.sections.each_with_index do |section, i| %>
              <li class="list-group-item"><%= i+1 %>.<%= link_to(section.section_name, admin_chapter_section_path(@chapter, section)) %></li>
            <% end %>
          </ul>
        </div>

      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
</section>